//
// Created by PC-SAMUEL on 21/12/2024.
//

#ifndef GROUNDED_MINIMAP_RESOURCES_H
#define GROUNDED_MINIMAP_RESOURCES_H

#define IDR_MAP_PNG 101
#define IDR_HOOPS_PNG 102
#define IDR_MAX_PNG 103
#define IDR_PETE_PNG 104
#define IDR_WILLOW_PNG 105

#endif //GROUNDED_MINIMAP_RESOURCES_H
